### ISSUE TITLE
I looked at the code, and I didn't find any information about the location of the building, maybe it was on the lower level, I couldn't find it

### ISSUE THREAD

**Issue by 1715187805** [sharknice/Sharky#26]
Hello, I used the Sharky Library, and I looked at his example of the Protoss bot code, which is the 4BG, how do you get the BG to be on the other side of the door, like the wild crystal vs example, but I don't understand how it works,

If you can, expect more beginner tutorials

**Comment by sharknice** [comment]
There is an example of that in at this file https://github.com/sharknice/Sharky/blob/master/SharkyProtossExampleBot/Builds/ProxyVoidRay.cs

ProxyTask = new ProxyTask(defaultSharkyBot, false, 0.9f, string.Empty, probeMicroController);

MicroTaskData[ProxyTask.ProxyName] = ProxyTask;
 var proxyLocation = ProxyLocationService.GetCliffProxyLocation();
MacroData.Proxies[ProxyTask.ProxyName] = new ProxyData(proxyLocation, MacroData);

 MacroData.Proxies[ProxyTask.ProxyName].DesiredProductionCounts[UnitTypes.PROTOSS_STARGATE] = 2;
